FROM jenkins/jenkins:lts
USER root

RUN apt-get update && apt-get install -y docker.io curl

# Installer docker compose v2 comme plugin CLI (pour que "docker compose" fonctionne)
RUN mkdir -p /usr/local/lib/docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-x86_64 \
    -o /usr/local/lib/docker/cli-plugins/docker-compose && \
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

USER jenkins